version: '3'
services:       
    app:
        container_name: nlw_copa_backend
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3333:3333'
        environment:
            - NODE_ENV=production
            - DATABASE_URL=file:/app/prisma/dev.db?timeout=5000
            - JWT_ACCESS_SECRET=nlwcopa