version: '3'
services:
    app:
        container_name: nlw_copa_frontend
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3003:3003'
        environment:
            - NODE_ENV=production